### ISSUE TITLE
Journals filter needs to recognise "olhj"

### ISSUE THREAD

**Issue by StephDriver** [openlibhums/hourglass#366]
Journals filter should recognise OLHJ and show The Open Library of Humanities Journal

<img width="379" alt="image" src="https://github.com/BirkbeckCTP/hourglass/assets/5330770/e95ae082-36c4-46d6-8eb5-ed45c88be5cd">

Currently journal description doesn't include this abbreviation either.
<img width="826" alt="image" src="https://github.com/BirkbeckCTP/hourglass/assets/5330770/e374805f-fb3b-45f1-a780-9678d3bb63ee">

Suggested fix:
 - Open Library of Humanities journal (OLHJ) is the flagship journal ...

**Comment by joemull** [comment]
Implemented this in the copy, after a conversation with Rose:

> _Open Library of Humanities_ Journal (OLHJ) is the flagship journal...
