### ISSUE TITLE
Copy to Clipboard button not working on supporters page.

### ISSUE THREAD

**Issue by mauromsl** [openlibhums/hourglass#406]
**Describe the bug**
When using the Copy to Clipboard function on the recommend-us page, it doesn't do anything, other than change its text to "Copied"

**To Reproduce**
1. Go to [recommend-us](https://www.openlibhums.org/plugins/supporters/recommend-us/)
2. Complete the form for a new institution
3. When the email text is presented, use the copy to clipboard function
4. Inspect your clipboard or try to paste

**Expected behavior**
Clipboard should be populated. In case of an error, it should be logged to console rather than swallowed.

**Screenshots**
![image](https://github.com/user-attachments/assets/d1cad464-1772-4d9f-b66f-411f5eee536c)

**Desktop (please complete the following information):**
System A
 - OS: Arch Linux
 - Browser Firefox
 - Version: Mozilla Firefox for Arch Linux 132.0
System B
 - OS: Windows
 - Browser: Chrome
 - Version: 130.0.6723.84

**Comment by StephDriver** [comment]
confirmed as replicated on MacOS with Chrome. (ie. not copied to clipboard)

Also, once copied, the button turns to 'copied' and doesn't work a second time - this is not helpful A11y wise, it is important that someone can do the same action again if for some reason they've then been interrupted before pasting.  

I suggest instead of `copy` -> `copied` have `copy`-> `copy again`

**Comment by joemull** [comment]
Confirmed with a discussion with Mauro and Steph that this was actually a mismatch between user expectation (that it pastes in places where plain text is supported, including a URL bar or a code editor), and design (that it pastes where html is supported, like an email editor window), as well as an apparent side effect on Arch Linux, where the clipboard manager does not recognize HTML copy events.

## Proposed solutions

- [ ] Use plain text, which has the advantage of working everywhere and allowing sender and recipient to examine full hyperlinks.
- [ ] Update the setting text to use plain text in openlibhums/consortial_billing
- [ ] As Steph suggests, also change the copy button text on copy to "copy again"
